spring:
  config:
    activate:
      on-profile: dev

  datasource:
    url: jdbc:postgresql://localhost:5432/spendwise_dev
    username: srinith
    password: srinith123
    driver-class-name: org.postgresql.Driver

  jpa:
    show-sql: true

